### ISSUE TITLE
Accessibility Issue - Link Text

### ISSUE THREAD

**Issue by astroash** [rachaelcodes/rachaelcodes.github.io#1]
All links are displayed as icons so there is no link text for visually impaired users. You can add hidden text so your site will look the same but screen readers will know where the links are taking them. Here's an example of how to hide content for visual:

```
<a href="babymayor.html" aria-label="Read more about Seminole's new baby mayor">[Read more...]</a>
 </p>
```

:)

**Comment by rachaelcodes** [comment]
neat - thanks!
